namespace KallyPoker.Tests;

public class CardTests
{
    [Theory]
    [InlineData(Suit.ClubsMask, Face.TwosMask, "2C")]
    [InlineData(Suit.ClubsMask, Face.ThreesMask, "3C")]
    [InlineData(Suit.ClubsMask, Face.FoursMask, "4C")]
    [InlineData(Suit.ClubsMask, Face.FivesMask, "5C")]
    [InlineData(Suit.ClubsMask, Face.SixesMask, "6C")]
    [InlineData(Suit.ClubsMask, Face.SevensMask, "7C")]
    [InlineData(Suit.ClubsMask, Face.EightsMask, "8C")]
    [InlineData(Suit.ClubsMask, Face.NinesMask, "9C")]
    [InlineData(Suit.ClubsMask, Face.TensMask, "TC")]
    [InlineData(Suit.ClubsMask, Face.JacksMask, "JC")]
    [InlineData(Suit.ClubsMask, Face.QueensMask, "QC")]
    [InlineData(Suit.ClubsMask, Face.KingsMask, "KC")]
    [InlineData(Suit.ClubsMask, Face.AcesMask, "AC")]
    [InlineData(Suit.DiamondsMask, Face.TwosMask, "2D")]
    [InlineData(Suit.DiamondsMask, Face.ThreesMask, "3D")]
    [InlineData(Suit.DiamondsMask, Face.FoursMask, "4D")]
    [InlineData(Suit.DiamondsMask, Face.FivesMask, "5D")]
    [InlineData(Suit.DiamondsMask, Face.SixesMask, "6D")]
    [InlineData(Suit.DiamondsMask, Face.SevensMask, "7D")]
    [InlineData(Suit.DiamondsMask, Face.EightsMask, "8D")]
    [InlineData(Suit.DiamondsMask, Face.NinesMask, "9D")]
    [InlineData(Suit.DiamondsMask, Face.TensMask, "TD")]
    [InlineData(Suit.DiamondsMask, Face.JacksMask, "JD")]
    [InlineData(Suit.DiamondsMask, Face.QueensMask, "QD")]
    [InlineData(Suit.DiamondsMask, Face.KingsMask, "KD")]
    [InlineData(Suit.DiamondsMask, Face.AcesMask, "AD")]
    [InlineData(Suit.HeartsMask, Face.TwosMask, "2H")]
    [InlineData(Suit.HeartsMask, Face.ThreesMask, "3H")]
    [InlineData(Suit.HeartsMask, Face.FoursMask, "4H")]
    [InlineData(Suit.HeartsMask, Face.FivesMask, "5H")]
    [InlineData(Suit.HeartsMask, Face.SixesMask, "6H")]
    [InlineData(Suit.HeartsMask, Face.SevensMask, "7H")]
    [InlineData(Suit.HeartsMask, Face.EightsMask, "8H")]
    [InlineData(Suit.HeartsMask, Face.NinesMask, "9H")]
    [InlineData(Suit.HeartsMask, Face.TensMask, "TH")]
    [InlineData(Suit.HeartsMask, Face.JacksMask, "JH")]
    [InlineData(Suit.HeartsMask, Face.QueensMask, "QH")]
    [InlineData(Suit.HeartsMask, Face.KingsMask, "KH")]
    [InlineData(Suit.HeartsMask, Face.AcesMask, "AH")]
    [InlineData(Suit.SpadesMask, Face.TwosMask, "2S")]
    [InlineData(Suit.SpadesMask, Face.ThreesMask, "3S")]
    [InlineData(Suit.SpadesMask, Face.FoursMask, "4S")]
    [InlineData(Suit.SpadesMask, Face.FivesMask, "5S")]
    [InlineData(Suit.SpadesMask, Face.SixesMask, "6S")]
    [InlineData(Suit.SpadesMask, Face.SevensMask, "7S")]
    [InlineData(Suit.SpadesMask, Face.EightsMask, "8S")]
    [InlineData(Suit.SpadesMask, Face.NinesMask, "9S")]
    [InlineData(Suit.SpadesMask, Face.TensMask, "TS")]
    [InlineData(Suit.SpadesMask, Face.JacksMask, "JS")]
    [InlineData(Suit.SpadesMask, Face.QueensMask, "QS")]
    [InlineData(Suit.SpadesMask, Face.KingsMask, "KS")]
    [InlineData(Suit.SpadesMask, Face.AcesMask, "AS")]
    public void TestStrings(ulong suitMask, ulong faceMask, string expected)
    {
        var actual = new Card(new Suit(suitMask), new Face(faceMask)).ToString();
        Assert.Equal(expected, actual);
    }
}